CREATE TYPE "NotificationType" AS ENUM ('NEW_MESSAGE','REQUEST_ACTION','EXPENSE_ACTION','HANDOVER_REMINDER','CALENDAR_REMINDER','DOCUMENT_ACTIVITY');
CREATE TABLE "Notification"("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"familyId" TEXT NOT NULL REFERENCES "Family"("id") ON DELETE RESTRICT,"type" "NotificationType" NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"title" TEXT NOT NULL,"dedupeKey" TEXT NOT NULL UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"readAt" TIMESTAMP(3));
CREATE TABLE "NotificationPreference"("userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"type" "NotificationType" NOT NULL,"inAppEnabled" BOOLEAN NOT NULL DEFAULT TRUE,"emailEnabled" BOOLEAN NOT NULL DEFAULT TRUE,"reminderLeadHours" INTEGER NOT NULL DEFAULT 24,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY("userId","type"),CHECK("reminderLeadHours" BETWEEN 1 AND 168));
CREATE TABLE "NotificationEmailOutbox"("id" TEXT PRIMARY KEY,"notificationId" TEXT NOT NULL UNIQUE REFERENCES "Notification"("id") ON DELETE RESTRICT,"status" "EmailDeliveryStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lockedAt" TIMESTAMP(3),"sentAt" TIMESTAMP(3),"providerMessageId" TEXT UNIQUE,"lastErrorCode" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId","readAt","createdAt"); CREATE INDEX "Notification_familyId_createdAt_idx" ON "Notification"("familyId","createdAt"); CREATE INDEX "NotificationEmailOutbox_status_nextAttemptAt_idx" ON "NotificationEmailOutbox"("status","nextAttemptAt");
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY; ALTER TABLE "NotificationPreference" ENABLE ROW LEVEL SECURITY; ALTER TABLE "NotificationEmailOutbox" ENABLE ROW LEVEL SECURITY;
CREATE POLICY notification_select ON "Notification" FOR SELECT TO coparent_runtime USING("userId"=current_coparent_user_id());
CREATE POLICY preference_select ON "NotificationPreference" FOR SELECT TO coparent_runtime USING("userId"=current_coparent_user_id());

CREATE FUNCTION prevent_notification_identity_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Notification records are permanent'; END IF; IF NEW."id" IS DISTINCT FROM OLD."id" OR NEW."userId" IS DISTINCT FROM OLD."userId" OR NEW."familyId" IS DISTINCT FROM OLD."familyId" OR NEW."type" IS DISTINCT FROM OLD."type" OR NEW."entityType" IS DISTINCT FROM OLD."entityType" OR NEW."entityId" IS DISTINCT FROM OLD."entityId" OR NEW."title" IS DISTINCT FROM OLD."title" OR NEW."dedupeKey" IS DISTINCT FROM OLD."dedupeKey" OR NEW."createdAt" IS DISTINCT FROM OLD."createdAt" THEN RAISE EXCEPTION 'Notification identity is immutable'; END IF; IF NEW."readAt" IS DISTINCT FROM OLD."readAt" AND nullif(current_setting('app.notification_transition_id',TRUE),'') IS DISTINCT FROM OLD."id" AND current_setting('app.notification_mark_all',TRUE) IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Notification read state requires a transition function'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER notification_protected BEFORE UPDATE OR DELETE ON "Notification" FOR EACH ROW EXECUTE FUNCTION prevent_notification_identity_mutation();

CREATE FUNCTION create_coparent_notification(target_user TEXT,target_family TEXT,target_type TEXT,target_entity_type TEXT,target_entity_id TEXT,target_title TEXT,target_dedupe TEXT) RETURNS TEXT LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$
DECLARE notification_id TEXT:=gen_random_uuid()::TEXT; in_app BOOLEAN; email BOOLEAN;
BEGIN
  SELECT coalesce((SELECT "inAppEnabled" FROM public."NotificationPreference" WHERE "userId"=target_user AND "type"=target_type::public."NotificationType"),TRUE),coalesce((SELECT "emailEnabled" FROM public."NotificationPreference" WHERE "userId"=target_user AND "type"=target_type::public."NotificationType"),TRUE) INTO in_app,email;
  IF NOT in_app AND NOT email THEN RETURN NULL; END IF;
  INSERT INTO public."Notification"("id","userId","familyId","type","entityType","entityId","title","dedupeKey","createdAt","readAt") VALUES(notification_id,target_user,target_family,target_type::public."NotificationType",target_entity_type,target_entity_id,target_title,target_dedupe,timezone('UTC',clock_timestamp()),CASE WHEN in_app THEN NULL ELSE timezone('UTC',clock_timestamp()) END) ON CONFLICT("dedupeKey") DO NOTHING RETURNING "id" INTO notification_id;
  IF notification_id IS NULL THEN RETURN NULL; END IF;
  IF email THEN INSERT INTO public."NotificationEmailOutbox"("id","notificationId","createdAt","updatedAt") VALUES(gen_random_uuid()::TEXT,notification_id,timezone('UTC',clock_timestamp()),timezone('UTC',clock_timestamp())); END IF;
  INSERT INTO public."AuditEvent"("id","familyId","actorId","action","entityType","entityId","occurredAt","metadata") VALUES(gen_random_uuid()::TEXT,target_family,NULL,'NOTIFICATION_CREATED','Notification',notification_id,timezone('UTC',clock_timestamp()),jsonb_build_object('type',target_type,'recipientId',target_user));
  RETURN notification_id;
EXCEPTION WHEN invalid_text_representation OR unique_violation OR foreign_key_violation THEN RETURN NULL;
END; $$;

CREATE FUNCTION notify_coparent_message() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ DECLARE recipient RECORD; BEGIN FOR recipient IN SELECT "userId" FROM public."FamilyMembership" WHERE "familyId"=NEW."familyId" AND "userId"<>NEW."senderId" LOOP PERFORM public.create_coparent_notification(recipient."userId",NEW."familyId",'NEW_MESSAGE','Message',NEW."id",'New family message','message:'||NEW."id"||':'||recipient."userId"); END LOOP; RETURN NEW; END; $$;
CREATE FUNCTION notify_coparent_request() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ BEGIN PERFORM public.create_coparent_notification(NEW."respondentId",NEW."familyId",'REQUEST_ACTION','FamilyRequest',NEW."id",'Family request awaiting your response','request:'||NEW."id"||':'||NEW."respondentId"); RETURN NEW; END; $$;
CREATE FUNCTION notify_coparent_expense() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ BEGIN PERFORM public.create_coparent_notification(NEW."respondentId",NEW."familyId",'EXPENSE_ACTION','Expense',NEW."id",'Expense awaiting your response','expense:'||NEW."id"||':'||NEW."respondentId"); RETURN NEW; END; $$;
CREATE TRIGGER message_notification AFTER INSERT ON "Message" FOR EACH ROW EXECUTE FUNCTION notify_coparent_message(); CREATE TRIGGER request_notification AFTER INSERT ON "FamilyRequest" FOR EACH ROW EXECUTE FUNCTION notify_coparent_request(); CREATE TRIGGER expense_notification AFTER INSERT ON "Expense" FOR EACH ROW EXECUTE FUNCTION notify_coparent_expense();

CREATE FUNCTION enqueue_coparent_due_reminders() RETURNS INTEGER LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ DECLARE candidate RECORD; total INTEGER:=0; created TEXT; BEGIN
  FOR candidate IN SELECT h."id",h."familyId",v."scheduledAt",u."userId",coalesce(p."reminderLeadHours",24) lead FROM public."Handover" h JOIN public."HandoverVersion" v ON v."id"=h."currentVersionId" CROSS JOIN LATERAL (VALUES(v."fromParentId"),(v."toParentId"))u("userId") LEFT JOIN public."NotificationPreference" p ON p."userId"=u."userId" AND p."type"='HANDOVER_REMINDER' WHERE v."state"='SCHEDULED' AND v."scheduledAt">timezone('UTC',clock_timestamp()) AND v."scheduledAt"<=timezone('UTC',clock_timestamp())+(coalesce(p."reminderLeadHours",24)||' hours')::interval LOOP SELECT public.create_coparent_notification(candidate."userId",candidate."familyId",'HANDOVER_REMINDER','Handover',candidate."id",'Upcoming family handover','handover-reminder:'||candidate."id"||':'||candidate."userId") INTO created; IF created IS NOT NULL THEN total:=total+1; END IF; END LOOP;
  FOR candidate IN SELECT e."id",e."familyId",v."startsAt",m."userId",coalesce(p."reminderLeadHours",24) lead FROM public."CalendarEvent" e JOIN public."CalendarEventVersion" v ON v."id"=e."currentVersionId" JOIN public."FamilyMembership" m ON m."familyId"=e."familyId" AND m."role" IN('OWNER','PARENT') LEFT JOIN public."NotificationPreference" p ON p."userId"=m."userId" AND p."type"='CALENDAR_REMINDER' WHERE v."state"='ACTIVE' AND v."startsAt">timezone('UTC',clock_timestamp()) AND v."startsAt"<=timezone('UTC',clock_timestamp())+(coalesce(p."reminderLeadHours",24)||' hours')::interval LOOP SELECT public.create_coparent_notification(candidate."userId",candidate."familyId",'CALENDAR_REMINDER','CalendarEvent',candidate."id",'Upcoming family calendar event','calendar-reminder:'||candidate."id"||':'||candidate."userId") INTO created; IF created IS NOT NULL THEN total:=total+1; END IF; END LOOP;
  RETURN total; END; $$;

CREATE FUNCTION mark_coparent_notification_read(target_id TEXT) RETURNS TIMESTAMP(3) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ DECLARE actor TEXT:=public.current_coparent_user_id(); result TIMESTAMP(3); BEGIN PERFORM set_config('app.notification_transition_id',target_id,TRUE); UPDATE public."Notification" SET "readAt"=coalesce("readAt",timezone('UTC',clock_timestamp())) WHERE "id"=target_id AND "userId"=actor RETURNING "readAt" INTO result; PERFORM set_config('app.notification_transition_id','',TRUE); RETURN result; END; $$;
CREATE FUNCTION mark_all_coparent_notifications_read() RETURNS INTEGER LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ DECLARE actor TEXT:=public.current_coparent_user_id(); affected INTEGER; BEGIN PERFORM set_config('app.notification_mark_all','true',TRUE); UPDATE public."Notification" SET "readAt"=timezone('UTC',clock_timestamp()) WHERE "userId"=actor AND "readAt" IS NULL; GET DIAGNOSTICS affected=ROW_COUNT; PERFORM set_config('app.notification_mark_all','',TRUE); RETURN affected; END; $$;
CREATE FUNCTION set_coparent_notification_preference(target_type TEXT,target_in_app BOOLEAN,target_email BOOLEAN,target_lead INTEGER) RETURNS BOOLEAN LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ DECLARE actor TEXT:=public.current_coparent_user_id(); BEGIN IF actor IS NULL OR target_lead NOT BETWEEN 1 AND 168 THEN RETURN FALSE; END IF; INSERT INTO public."NotificationPreference"("userId","type","inAppEnabled","emailEnabled","reminderLeadHours","updatedAt") VALUES(actor,target_type::public."NotificationType",target_in_app,target_email,target_lead,timezone('UTC',clock_timestamp())) ON CONFLICT("userId","type") DO UPDATE SET "inAppEnabled"=EXCLUDED."inAppEnabled","emailEnabled"=EXCLUDED."emailEnabled","reminderLeadHours"=EXCLUDED."reminderLeadHours","updatedAt"=EXCLUDED."updatedAt"; RETURN TRUE; EXCEPTION WHEN invalid_text_representation THEN RETURN FALSE; END; $$;

CREATE FUNCTION claim_coparent_notification_email_outbox(batch_size INTEGER DEFAULT 10) RETURNS TABLE("jobId" TEXT,"notificationId" TEXT,"recipient" TEXT,"title" TEXT,"type" TEXT,"attempts" INTEGER) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ BEGIN RETURN QUERY WITH jobs AS (SELECT o."id" FROM public."NotificationEmailOutbox" o WHERE o."status" IN('PENDING','RETRY') AND o."nextAttemptAt"<=timezone('UTC',clock_timestamp()) AND (o."lockedAt" IS NULL OR o."lockedAt"<timezone('UTC',clock_timestamp())-interval '5 minutes') ORDER BY o."createdAt" FOR UPDATE SKIP LOCKED LIMIT greatest(1,least(batch_size,100))), updated AS (UPDATE public."NotificationEmailOutbox" o SET "status"='PROCESSING',"lockedAt"=timezone('UTC',clock_timestamp()),"attempts"=o."attempts"+1,"updatedAt"=timezone('UTC',clock_timestamp()) FROM jobs WHERE o."id"=jobs."id" RETURNING o.*) SELECT u."id",n."id",usr."email",n."title",n."type"::TEXT,u."attempts" FROM updated u JOIN public."Notification" n ON n."id"=u."notificationId" JOIN public."User" usr ON usr."id"=n."userId"; END; $$;
CREATE FUNCTION complete_coparent_notification_email(target_job TEXT,target_provider_id TEXT) RETURNS BOOLEAN LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ BEGIN UPDATE public."NotificationEmailOutbox" SET "status"='SENT',"sentAt"=timezone('UTC',clock_timestamp()),"providerMessageId"=target_provider_id,"lockedAt"=NULL,"lastErrorCode"=NULL,"updatedAt"=timezone('UTC',clock_timestamp()) WHERE "id"=target_job AND "status"='PROCESSING'; RETURN FOUND; END; $$;
CREATE FUNCTION retry_coparent_notification_email(target_job TEXT,target_error TEXT,target_retry TIMESTAMPTZ,target_terminal BOOLEAN) RETURNS BOOLEAN LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET timezone='UTC' AS $$ BEGIN UPDATE public."NotificationEmailOutbox" SET "status"=CASE WHEN target_terminal THEN 'FAILED'::public."EmailDeliveryStatus" ELSE 'RETRY'::public."EmailDeliveryStatus" END,"nextAttemptAt"=target_retry,"lockedAt"=NULL,"lastErrorCode"=left(target_error,100),"updatedAt"=timezone('UTC',clock_timestamp()) WHERE "id"=target_job AND "status"='PROCESSING'; RETURN FOUND; END; $$;

REVOKE ALL ON FUNCTION create_coparent_notification(TEXT,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT),enqueue_coparent_due_reminders(),mark_coparent_notification_read(TEXT),mark_all_coparent_notifications_read(),set_coparent_notification_preference(TEXT,BOOLEAN,BOOLEAN,INTEGER),claim_coparent_notification_email_outbox(INTEGER),complete_coparent_notification_email(TEXT,TEXT),retry_coparent_notification_email(TEXT,TEXT,TIMESTAMPTZ,BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION enqueue_coparent_due_reminders(),mark_coparent_notification_read(TEXT),mark_all_coparent_notifications_read(),set_coparent_notification_preference(TEXT,BOOLEAN,BOOLEAN,INTEGER),claim_coparent_notification_email_outbox(INTEGER),complete_coparent_notification_email(TEXT,TEXT),retry_coparent_notification_email(TEXT,TEXT,TIMESTAMPTZ,BOOLEAN) TO coparent_runtime;
GRANT SELECT ON "Notification","NotificationPreference" TO coparent_runtime;
